name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Doxygen Documentation
      run: |
        doxygen Doxyfile

    - name: Deploy HTML Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
